### ISSUE TITLE
Fix print method

### ISSUE THREAD

**Issue by mmulvahill** [KechrisLab/MSPrep#21]
Doesn't seem to be working across the entire pipeline.

**Comment by DanielMedic** [comment]
This ties in with the issue raised by @kechrisk that the "Final Output" section of the vignette is empty.  Once every object has a good `print` method, the vignette can be filled in.  Line 176 of prepare.r has the beginnings of the method.

**Comment by DanielMedic** [comment]
Odd little chunk in the vignette:

"Identifiers in the datasets
- LCMS_Run_ID = operator/replicate (A-C), subject (01-03), concentration  (1x,2x,4x)
- SubjectID   = subject (01-03), concentration  (1x,2x,4x)"

Per @mmulvahill this is the beginning of documentation for the data set.  I will either fully document or clean it up entirely.
