### ISSUE TITLE
Add documentation to functions, datasets, and add vignette

### ISSUE THREAD

**Issue by mmulvahill** [KechrisLab/MSPrep#3]

**Comment by DanielMedic** [comment]
Odd little chunk in the vignette pointed out by @kechrisk :

"Identifiers in the datasets - LCMS_Run_ID = operator/replicate (A-C), subject (01-03), concentration (1x,2x,4x) - SubjectID = subject (01-03), concentration (1x,2x,4x)"

Per @mmulvahill this is the beginning of documentation for the data set. I will either fully document or delete it.

**Comment by DanielMedic** [comment]
I will fill in the final output section of the vignette once the `print` methods are up to date as specified in <https://github.com/KechrisLab/MSPrep/issues/21>

**Comment by DanielMedic** [comment]
In answer to a question from @kechrisk : the coefficient of variation cutoff in `ms_prepare` is given by the `cvmax` parameter, current default 0.5.

**Comment by DanielMedic** [comment]
The line "a list of the column numbers containing them should be provided in the controls variable" in the vignette is ambiguous.  @kechrisk notes, "The data is provided where compounds are rows, so what does column numbers mean here?"  I think this means that if there are control _subjects_ in the data set, a vector containing their indices should be passed as the `controls` argument.  I will investigate and fix the documentation.
